version: 'v0.2-{build}-wintest'
branches:
  only:
  - main
skip_tags: true

environment:
  HAXELIB_ROOT: C:\projects\haxelib
  HAXE_INSTALLDIR: C:\projects\haxe
  SRC_REPO: https://github.com/aflacc/ProjectFNF.git
  GITHUB_ACCESS_TOKEN:
    secure: AYoRbFDfZVEdfVVzZFuz5wJXJkAEOOkHtgAweikYp3tqImQUhwg2P6dCjyPxEF7o

install:
  # http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
  - ps: Set-Service wuauserv -StartupType Manual
  # Install the neko chocolatey package (https://chocolatey.org/packages/neko)
  - cinst neko --version 2.3.0 -y
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe --version 4.1.5 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # Install project dependencies
  - haxelib install lime 7.9.0
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  # haxelib run flixel-tools setup -y # Can't do this since it asks [y/n] even with -y argument! Stupid
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib install flixel-addons
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib install linc_luajit
  - haxelib list
  - git clone "%SRC_REPO%" C:\projects\src
build_script:
  - cd C:\projects\src\source
  - mkdir C:\projects\src\source\ugh\
  - git clone https://github.com/Derpy-Jacob-903/APIStuff.git C:\projects\src\source\ugh\
  - cd C:\projects\src\source\ugh\
  - cp APIStuff.hx C:\projects\src\source\
  - ls C:\projects\src\source\ugh\
  - git config --global credential.helper store
  - printf "https://$GITHUB_ACCESS_TOKEN:x-oauth-basic@github.com\n" > $HOME/.git-credentials
  - git config --global user.email "mycatisagoodboi@gmail.com"
  - git config --global user.name "Derpy-Jacob-903"
  - cd C:\projects\src\
  - haxelib run lime build windows
  
artifacts:
  - path: C:\projects/export/release/windows/bin
    name: projectFNF-Windows
    type: zip
